name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9, 3.8, 3.7, 3.6]

    steps:

      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
          poetry install

      - name: Run tests
        run: |
          poetry run flake8 --ignore E501,W503 example/
          poetry run flake8 --ignore E501,W503 tests/
          poetry run pytest
